name: Build APK
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'
      - name: Build
        run: |
          ls -la
          rm -rf project
          unzip -o -q FFTraceScanner_v3_source.zip -d project
          DIR=$(dirname "$(find project -name 'settings.gradle*' | head -n 1)")
          cd "$DIR"
          gradle assembleDebug --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: FFTraceScanner-v3-debug-apk
          path: project/**/app/build/outputs/apk/debug/*.apk
